apiVersion: apps/v1
kind: Deployment
metadata:
  name: quickstart
spec:
  selector:
    matchLabels:
      app: quickstart
  replicas: 2
  template:
    metadata:
      labels:
        app: quickstart
    spec:
      containers:
      - name: quickstart
        image: asia-southeast2-docker.pkg.dev/sandbox-kompasid-poc/quickstart/quickstart-image:tag1
        ports:
        - containerPort: 80
